### ISSUE TITLE
adding old projects to readme

### ISSUE THREAD

**Issue by abhijithvijayan** [ceadoor/activities#3]
### Note

For the contributors, Please take one project to add to readme and leave another for other contributors. Do comment on the one you are taking.

- [x] Glitch 2.0
- [x] library_management_ci
- [ ] facebook-coverpic-gen

**Comment by abhijithvijayan** [comment]
#### Name:
Glitch 2.0 
#### url:
https://github.com/ceadoor/glitch-2.0
#### Description:
Online sea maze game done for AAROH 19
#### Badge:
`[![Status: Complete](https://img.shields.io/badge/status-complete-blue.svg)](https://github.com/ceadoor/glitch-2.0/commits/master)`
#### Tech used:
- Express
- Passport.js
- MongoDB
- Pug

in between CEA Website & TRACE Website

**Comment by abhijithvijayan** [comment]
library_management_ci
https://github.com/ceadoor/library_management_ci
- Javascript
- PHP
- Bootstrap

**Comment by Le-Morri** [comment]
Hey, happy to do the "library_management_ci". THough wich status-badge do you whish to have to the project?

**Comment by abhijithvijayan** [comment]
> Hey, happy to do the "library_management_ci". THough wich status-badge do you whish to have to the project?

Requires `status: complete` badge

**Comment by abhijithvijayan** [comment]
#### Name:
facebook-coverpic-gen
#### url:
https://github.com/ceadoor/facebook-coverpic-gen
#### Description:
Facebook cover pic generator for aaroh 2k18
#### Badge:
`[![Status: Complete](https://img.shields.io/badge/status-complete-blue.svg)](https://github.com/ceadoor/facebook-coverpic-gen/commits/master)`
#### Tech used:
- Angular
- Express
- Ejs

**Comment by najafmohammed** [comment]
I will Update Glitch2.0 to Readme
